package com.zhiguan.carownerhomecrm.domain.user;

import java.util.Date;

public class UserBaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.id
     *
     * @mbggenerated
     */
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.is_Deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.create_Operator
     *
     * @mbggenerated
     */
    private String createOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.last_Operator
     *
     * @mbggenerated
     */
    private String lastOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.last_Modify_Time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.inside_uid
     *
     * @mbggenerated
     */
    private String insideUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.weixin_openid
     *
     * @mbggenerated
     */
    private String weixinOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.if_wx_public
     *
     * @mbggenerated
     */
    private String ifWxPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.if_wx_xiao
     *
     * @mbggenerated
     */
    private String ifWxXiao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.weixin_num
     *
     * @mbggenerated
     */
    private String weixinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.vice_number
     *
     * @mbggenerated
     */
    private String viceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.provice
     *
     * @mbggenerated
     */
    private String provice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.img_url_weixin_max
     *
     * @mbggenerated
     */
    private String imgUrlWeixinMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.img_url_weixin_min
     *
     * @mbggenerated
     */
    private String imgUrlWeixinMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.car_color
     *
     * @mbggenerated
     */
    private String carColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.car_type_id
     *
     * @mbggenerated
     */
    private Long carTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.car_type_is_secret
     *
     * @mbggenerated
     */
    private String carTypeIsSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.car_photo_url
     *
     * @mbggenerated
     */
    private String carPhotoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.activity_area
     *
     * @mbggenerated
     */
    private String activityArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.sign_desc
     *
     * @mbggenerated
     */
    private String signDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.person_state
     *
     * @mbggenerated
     */
    private String personState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.good_count
     *
     * @mbggenerated
     */
    private Integer goodCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.secret_count
     *
     * @mbggenerated
     */
    private Integer secretCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.member_out_date
     *
     * @mbggenerated
     */
    private Date memberOutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.phone_number
     *
     * @mbggenerated
     */
    private Integer phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.phone_verrification_code
     *
     * @mbggenerated
     */
    private String phoneVerrificationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.bak4
     *
     * @mbggenerated
     */
    private String bak4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.bak5
     *
     * @mbggenerated
     */
    private String bak5;

    //模糊查询字段
    private String likeName;
    private int pageStart;
    private int limit;
    private int currPage;


    private Long customerId;



    public String getLikeName() {
        return likeName;
    }

    public void setLikeName(String likeName) {
        this.likeName = likeName;
    }

    public int getPageStart() {
        return pageStart;
    }

    public void setPageStart(int pageStart) {
        this.pageStart = pageStart;
    }

    public int getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }

    public int getCurrPage() {
        return currPage;
    }

    public void setCurrPage(int currPage) {
        this.currPage = currPage;
    }






    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.is_Deleted
     *
     * @return the value of user_base_info.is_Deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.is_Deleted
     *
     * @param isDeleted the value for user_base_info.is_Deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.create_Operator
     *
     * @return the value of user_base_info.create_Operator
     *
     * @mbggenerated
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.create_Operator
     *
     * @param createOperator the value for user_base_info.create_Operator
     *
     * @mbggenerated
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.create_time
     *
     * @return the value of user_base_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.create_time
     *
     * @param createTime the value for user_base_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.last_Operator
     *
     * @return the value of user_base_info.last_Operator
     *
     * @mbggenerated
     */
    public String getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.last_Operator
     *
     * @param lastOperator the value for user_base_info.last_Operator
     *
     * @mbggenerated
     */
    public void setLastOperator(String lastOperator) {
        this.lastOperator = lastOperator == null ? null : lastOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.last_Modify_Time
     *
     * @return the value of user_base_info.last_Modify_Time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.last_Modify_Time
     *
     * @param lastModifyTime the value for user_base_info.last_Modify_Time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.inside_uid
     *
     * @return the value of user_base_info.inside_uid
     *
     * @mbggenerated
     */
    public String getInsideUid() {
        return insideUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.inside_uid
     *
     * @param insideUid the value for user_base_info.inside_uid
     *
     * @mbggenerated
     */
    public void setInsideUid(String insideUid) {
        this.insideUid = insideUid == null ? null : insideUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.org_id
     *
     * @return the value of user_base_info.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.org_id
     *
     * @param orgId the value for user_base_info.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.nick_name
     *
     * @return the value of user_base_info.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.nick_name
     *
     * @param nickName the value for user_base_info.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.weixin_openid
     *
     * @return the value of user_base_info.weixin_openid
     *
     * @mbggenerated
     */
    public String getWeixinOpenid() {
        return weixinOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.weixin_openid
     *
     * @param weixinOpenid the value for user_base_info.weixin_openid
     *
     * @mbggenerated
     */
    public void setWeixinOpenid(String weixinOpenid) {
        this.weixinOpenid = weixinOpenid == null ? null : weixinOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.if_wx_public
     *
     * @return the value of user_base_info.if_wx_public
     *
     * @mbggenerated
     */
    public String getIfWxPublic() {
        return ifWxPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.if_wx_public
     *
     * @param ifWxPublic the value for user_base_info.if_wx_public
     *
     * @mbggenerated
     */
    public void setIfWxPublic(String ifWxPublic) {
        this.ifWxPublic = ifWxPublic == null ? null : ifWxPublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.if_wx_xiao
     *
     * @return the value of user_base_info.if_wx_xiao
     *
     * @mbggenerated
     */
    public String getIfWxXiao() {
        return ifWxXiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.if_wx_xiao
     *
     * @param ifWxXiao the value for user_base_info.if_wx_xiao
     *
     * @mbggenerated
     */
    public void setIfWxXiao(String ifWxXiao) {
        this.ifWxXiao = ifWxXiao == null ? null : ifWxXiao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.sex
     *
     * @return the value of user_base_info.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.sex
     *
     * @param sex the value for user_base_info.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.state
     *
     * @return the value of user_base_info.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.state
     *
     * @param state the value for user_base_info.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.weixin_num
     *
     * @return the value of user_base_info.weixin_num
     *
     * @mbggenerated
     */
    public String getWeixinNum() {
        return weixinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.weixin_num
     *
     * @param weixinNum the value for user_base_info.weixin_num
     *
     * @mbggenerated
     */
    public void setWeixinNum(String weixinNum) {
        this.weixinNum = weixinNum == null ? null : weixinNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.vice_number
     *
     * @return the value of user_base_info.vice_number
     *
     * @mbggenerated
     */
    public String getViceNumber() {
        return viceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.vice_number
     *
     * @param viceNumber the value for user_base_info.vice_number
     *
     * @mbggenerated
     */
    public void setViceNumber(String viceNumber) {
        this.viceNumber = viceNumber == null ? null : viceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.country
     *
     * @return the value of user_base_info.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.country
     *
     * @param country the value for user_base_info.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.provice
     *
     * @return the value of user_base_info.provice
     *
     * @mbggenerated
     */
    public String getProvice() {
        return provice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.provice
     *
     * @param provice the value for user_base_info.provice
     *
     * @mbggenerated
     */
    public void setProvice(String provice) {
        this.provice = provice == null ? null : provice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.city
     *
     * @return the value of user_base_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.city
     *
     * @param city the value for user_base_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.img_url_weixin_max
     *
     * @return the value of user_base_info.img_url_weixin_max
     *
     * @mbggenerated
     */
    public String getImgUrlWeixinMax() {
        return imgUrlWeixinMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.img_url_weixin_max
     *
     * @param imgUrlWeixinMax the value for user_base_info.img_url_weixin_max
     *
     * @mbggenerated
     */
    public void setImgUrlWeixinMax(String imgUrlWeixinMax) {
        this.imgUrlWeixinMax = imgUrlWeixinMax == null ? null : imgUrlWeixinMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.img_url_weixin_min
     *
     * @return the value of user_base_info.img_url_weixin_min
     *
     * @mbggenerated
     */
    public String getImgUrlWeixinMin() {
        return imgUrlWeixinMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.img_url_weixin_min
     *
     * @param imgUrlWeixinMin the value for user_base_info.img_url_weixin_min
     *
     * @mbggenerated
     */
    public void setImgUrlWeixinMin(String imgUrlWeixinMin) {
        this.imgUrlWeixinMin = imgUrlWeixinMin == null ? null : imgUrlWeixinMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.car_color
     *
     * @return the value of user_base_info.car_color
     *
     * @mbggenerated
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.car_color
     *
     * @param carColor the value for user_base_info.car_color
     *
     * @mbggenerated
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.car_type_id
     *
     * @return the value of user_base_info.car_type_id
     *
     * @mbggenerated
     */
    public Long getCarTypeId() {
        return carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.car_type_id
     *
     * @param carTypeId the value for user_base_info.car_type_id
     *
     * @mbggenerated
     */
    public void setCarTypeId(Long carTypeId) {
        this.carTypeId = carTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.car_type_is_secret
     *
     * @return the value of user_base_info.car_type_is_secret
     *
     * @mbggenerated
     */
    public String getCarTypeIsSecret() {
        return carTypeIsSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.car_type_is_secret
     *
     * @param carTypeIsSecret the value for user_base_info.car_type_is_secret
     *
     * @mbggenerated
     */
    public void setCarTypeIsSecret(String carTypeIsSecret) {
        this.carTypeIsSecret = carTypeIsSecret == null ? null : carTypeIsSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.car_photo_url
     *
     * @return the value of user_base_info.car_photo_url
     *
     * @mbggenerated
     */
    public String getCarPhotoUrl() {
        return carPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.car_photo_url
     *
     * @param carPhotoUrl the value for user_base_info.car_photo_url
     *
     * @mbggenerated
     */
    public void setCarPhotoUrl(String carPhotoUrl) {
        this.carPhotoUrl = carPhotoUrl == null ? null : carPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.activity_area
     *
     * @return the value of user_base_info.activity_area
     *
     * @mbggenerated
     */
    public String getActivityArea() {
        return activityArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.activity_area
     *
     * @param activityArea the value for user_base_info.activity_area
     *
     * @mbggenerated
     */
    public void setActivityArea(String activityArea) {
        this.activityArea = activityArea == null ? null : activityArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.sign_desc
     *
     * @return the value of user_base_info.sign_desc
     *
     * @mbggenerated
     */
    public String getSignDesc() {
        return signDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.sign_desc
     *
     * @param signDesc the value for user_base_info.sign_desc
     *
     * @mbggenerated
     */
    public void setSignDesc(String signDesc) {
        this.signDesc = signDesc == null ? null : signDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.person_state
     *
     * @return the value of user_base_info.person_state
     *
     * @mbggenerated
     */
    public String getPersonState() {
        return personState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.person_state
     *
     * @param personState the value for user_base_info.person_state
     *
     * @mbggenerated
     */
    public void setPersonState(String personState) {
        this.personState = personState == null ? null : personState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.good_count
     *
     * @return the value of user_base_info.good_count
     *
     * @mbggenerated
     */
    public Integer getGoodCount() {
        return goodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.good_count
     *
     * @param goodCount the value for user_base_info.good_count
     *
     * @mbggenerated
     */
    public void setGoodCount(Integer goodCount) {
        this.goodCount = goodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.secret_count
     *
     * @return the value of user_base_info.secret_count
     *
     * @mbggenerated
     */
    public Integer getSecretCount() {
        return secretCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.secret_count
     *
     * @param secretCount the value for user_base_info.secret_count
     *
     * @mbggenerated
     */
    public void setSecretCount(Integer secretCount) {
        this.secretCount = secretCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.member_out_date
     *
     * @return the value of user_base_info.member_out_date
     *
     * @mbggenerated
     */
    public Date getMemberOutDate() {
        return memberOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.member_out_date
     *
     * @param memberOutDate the value for user_base_info.member_out_date
     *
     * @mbggenerated
     */
    public void setMemberOutDate(Date memberOutDate) {
        this.memberOutDate = memberOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.phone_number
     *
     * @return the value of user_base_info.phone_number
     *
     * @mbggenerated
     */
    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.phone_number
     *
     * @param phoneNumber the value for user_base_info.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.phone_verrification_code
     *
     * @return the value of user_base_info.phone_verrification_code
     *
     * @mbggenerated
     */
    public String getPhoneVerrificationCode() {
        return phoneVerrificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.phone_verrification_code
     *
     * @param phoneVerrificationCode the value for user_base_info.phone_verrification_code
     *
     * @mbggenerated
     */
    public void setPhoneVerrificationCode(String phoneVerrificationCode) {
        this.phoneVerrificationCode = phoneVerrificationCode == null ? null : phoneVerrificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.bak1
     *
     * @return the value of user_base_info.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.bak1
     *
     * @param bak1 the value for user_base_info.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.bak2
     *
     * @return the value of user_base_info.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.bak2
     *
     * @param bak2 the value for user_base_info.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.bak3
     *
     * @return the value of user_base_info.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.bak3
     *
     * @param bak3 the value for user_base_info.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.bak4
     *
     * @return the value of user_base_info.bak4
     *
     * @mbggenerated
     */
    public String getBak4() {
        return bak4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.bak4
     *
     * @param bak4 the value for user_base_info.bak4
     *
     * @mbggenerated
     */
    public void setBak4(String bak4) {
        this.bak4 = bak4 == null ? null : bak4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.bak5
     *
     * @return the value of user_base_info.bak5
     *
     * @mbggenerated
     */
    public String getBak5() {
        return bak5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base_info.bak5
     *
     * @param bak5 the value for user_base_info.bak5
     *
     * @mbggenerated
     */
    public void setBak5(String bak5) {
        this.bak5 = bak5 == null ? null : bak5.trim();
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}